# Generated by Django 4.2.3 on 2023-07-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_rename_usuario_planta_usuario_id_planta_nombreu'),
        ('SIL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intensidaddeluz',
            name='planta_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plants.planta'),
        ),
    ]
