# Generated by Django 4.2.3 on 2023-07-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_historicaluser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
