# Generated by Django 4.2.3 on 2023-07-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.AddField(
            model_name='planta',
            name='nombreU',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de Usuario'),
        ),
    ]
