# Generated by Django 4.2.3 on 2023-07-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_rename_usuario_planta_usuario_id_planta_nombreu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
