# Generated by Django 4.2.3 on 2023-07-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SHA', '0001_initial'),
        ('SHS', '0001_initial'),
        ('ST', '0002_temperatura_valor'),
        ('SIL', '0003_rename_planta_id_intensidaddeluz_planta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('humedadAmbiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SHA.humedaddeambiente')),
                ('humedadSuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SHS.humedaddesuelo')),
                ('intensidadLuz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIL.intensidaddeluz')),
                ('temperatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ST.temperatura')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
